#!/bin/env python3

import os
import shutil
import sys
import argparse
import tomllib


# parse command line flags
parser = argparse.ArgumentParser(
    description = "A tool for dumb file versioning",
    usage = "",
    epilog = ""
)
parser.add_argument(
    "product_path",
    nargs="?",
    default="."
)

args = parser.parse_args()

# go to the product directory
os.chdir(args.product_path)


# load product configration
global config
with open("./.phase","rb") as fp:
    config = tomllib.load(fp)


print(config)

config["pattern"] = config["pattern"]\
        .replace("%V",r"(\d+)")\
        .replace(".",r"\.")


print(config)
